### ISSUE TITLE
Failed to instantiate

### ISSUE THREAD

**Issue by czmarcos** [yaru22/angular-timeago#81]
Installed with bower and tried to include in my ionic project, however it shows this error:

ionic.bundle.js:13380 
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module yaru22.angular-timeago due to:
Error: [$injector:nomod] Module 'yaru22.angular-timeago' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.3/$injector/nomod?p0=yaru22.angular-timeago
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:13380:12
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:15270:17
    at ensure (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15194:38)
    at module (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15268:14)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17674:22
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13648:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17658:5)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17675:40
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13648:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17658:5)
http://errors.angularjs.org/1.4.3/$injector/modulerr?p0=yaru22.angular-time…%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17658%3A5)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:13380:12
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17697:15
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13648:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17658:5)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17675:40
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13648:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17658:5)
    at createInjector (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17584:11)
    at doBootstrap (http://localhost:8100/lib/ionic/js/ionic.bundle.js:14942:20)
    at bootstrap (http://localhost:8100/lib/ionic/js/ionic.bundle.js:14963:12)
http://errors.angularjs.org/1.4.3/$injector/modulerr?p0=app&p1=Error%3A%20%…3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A14963%3A12)

**Comment by yaru22** [comment]
Did you add `yaru22.angular-timeago` as a dependency to your module?

e.g.
```
var app = angular.module('ngApp', [
  'yaru22.angular-timeago'
]);
```

**Comment by czmarcos** [comment]
Hi, yes I did include! Tried without 'yary22' as well, but didn't work. It shows the error that I mentioned before.

**Comment by astik** [comment]
I just test with a blank project and everything seems to work.
Here are the steps i did to try to reproduce your issue :

	ionic -v
	=> 1.7.16
	# init a blank project
	ionic start myApp blank
	cd myApp
	ionic serve
	# project is working as expected
	bower install --save angular-timeago
	=> install angular-timeago#0.4.3
	# add 'yaru22.angular-timeago' as a dependency
	angular.module('starter', ['ionic', 'yaru22.angular-timeago'])
	# add library declaration
	<script src="lib/angular-timeago/dist/angular-timeago.js"></script>
	# define a controller
	angular.module('starter').controller('MyCtrl', function(){
		this.date = new Date();
	});
	# change ion-content
	<ion-content ng-controller="MyCtrl as ctrl">
		{{ctrl.date | timeAgo}}
	</ion-content>

Can you share with us a project example for us to check and debug the problem ?

**Comment by czmarcos** [comment]
Thanks a lot @astik. I forgot to include <script src="lib/angular-timeago/dist/angular-timeago.js"></script>on my index.html file!
